file_format: "1"
id: charybdis_nano
name: Charybdis_nano
type: shield
url: https://github.com/Bastardkb/Charybdis/
requires: [pro_micro]
features:
  - keys
  - pointer
  - underglow
siblings:
  - charybdis_nano_left
  - charybdis_nano_right
